<?xml?>
<productos>
    <producto>
        <codigo>1</codigo>
    </producto>
    <producto>
        <codigo>2</codigo>
    </producto>
    <producto>
        <codigo>3</codigo>
    </producto>
</productos>