<?php

return array(
    'urlFormat' => 'path',
    'showScriptName' => false,
    'caseSensitive' => true,
    'rules' => array(
        /* 'post/<id:\d+>/<title:.*?>'=>'post/view',
          'posts/<tag:.*?>'=>'post/index', */

        // Links de campañias
        'atacadol-alivio-dolores-fuertes' => 'publicidad/contenido/nombre/atacadol-alivio-dolores-fuertes',
        'coca-cola-sabores' => 'publicidad/contenido/nombre/coca-cola-sabores',
        'corega' => 'publicidad/contenido/nombre/corega',
        'klim-fortigrow' => 'publicidad/contenido/nombre/klim-fortigrow',
        'klim1-fortiprotect' => 'publicidad/contenido/nombre/leche-klim-1',
        'listerine' => 'publicidad/contenido/nombre/listerine-cuidado-total',
        'mas-informacion-metamucil' => 'publicidad/contenido/nombre/mas-informacion-metamucil',
        'metamucil-facilita-transito-intestinal' => 'publicidad/contenido/nombre/metamucil-facilita-transito-intestinal',
        'nestle-nan-optipro' => 'publicidad/contenido/nombre/nestle-nan-optipro',
        'recetas-nestle-nan-optipro' => 'publicidad/contenido/nombre/nan-recetas',
        // 'mas-informacion-nan' => 'publicidad/contenido/nombre/mas-informacion-nan',
        'parodontax' => 'publicidad/contenido/nombre/parodontax',
        'porque-elejir-metamucil' => 'publicidad/contenido/nombre/porque-elejir-metamucil',
        'prebioticos-klim' => 'publicidad/contenido/nombre/prebioticos-klim',
        'prohelix' => 'publicidad/contenido/nombre/prohelix',
        'sensodyne' => 'publicidad/contenido/nombre/sensodyne',
        'sobre-metamucil' => 'publicidad/contenido/nombre/sobre-metamucil',
        'perros-y-gatos' => 'publicidad/contenido/nombre/perros-y-gatos',
        'muestra-gratis-perros-y-gatos' => 'publicidad/contenido/nombre/perros-y-gatos-formulario',
        'proteccion-solar-sol-or' => 'publicidad/contenido/nombre/sol-or',
        'shampoo-clinical-solution-caspa-severa' => 'publicidad/contenido/nombre/pyg',
        'similac-mama-embarazo' => 'publicidad/contenido/nombre/similac-mama',
        'similac-3kid' => 'publicidad/contenido/nombre/similac-3-kid',
        'pediasure' => 'publicidad/contenido/nombre/pediasure',
        'ensure-nutricion-especializada' => 'publicidad/contenido/nombre/ensure',
        'glucerna-para-diabeticos' => 'publicidad/contenido/nombre/glucerna',
        'zahara-protector-solar' => 'publicidad/contenido/nombre/zahara',
        'zahara-protector-solar-kids' => 'publicidad/contenido/nombre/zahara-kids',
        'zahara-bronceador' => 'publicidad/contenido/nombre/zahara-bronceador',
        'prodent-cuidado-oral-old' => 'publicidad/contenido/nombre/prodent-old',
        'prodent-cuidado-oral' => 'publicidad/contenido/nombre/prodent',
        'prodent-cuidado-oral-ninos' => 'publicidad/contenido/nombre/prodent-ninos',
        'prodent-ennjuague-bucal' => 'publicidad/contenido/nombre/prodent-enjuague',
        'pedialyte-suero-oral' => 'publicidad/contenido/nombre/pedialyte',
        'pilas-energizer' => 'publicidad/contenido/nombre/energizer',
        'pilas-especiales-energizer' => 'publicidad/contenido/nombre/energizer-pilas-especiales',
        'pilas-auditivas-energizer' => 'publicidad/contenido/nombre/energizer-pilas-auditivas',
        'pilas-recargables-energizer' => 'publicidad/contenido/nombre/energizer-pilas-recargables',
        'condones-duo-sensaciones-extremas' => 'publicidad/contenido/nombre/duo-sensaciones-extremas',
        'condones-duo-maxima-sensacion' => 'publicidad/contenido/nombre/duo-maxima-sensacion',
        'condones-duo-seguridad-y-confianza' => 'publicidad/contenido/nombre/duo-seguridad-y-confianza',
        'altex-previene-acne' => 'publicidad/contenido/nombre/altex-previene',
        'altex-elimina-acne' => 'publicidad/contenido/nombre/altex-elimina',
        'altex-oculta-acne' => 'publicidad/contenido/nombre/altex-oculta',
        'cicatricure' => 'publicidad/contenido/nombre/cicatricure',
        'cicatricure-gel' => 'publicidad/contenido/nombre/cicatricure-gel',
        'cicatricure-contorno-ojos' => 'publicidad/contenido/nombre/cicatricure-ojos',
        'cicatricure-beauty-care' => 'publicidad/contenido/nombre/cicatricure-beauty',
        'cicatricure-crema' => 'publicidad/contenido/nombre/cicatricure-crema',
        'electrohogar' => 'publicidad/contenido/nombre/electrohogar',
        'nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum',
        'recetas-nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum-recetas',
        'sabias-que-nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum-sabias-que',
        'eucerin-proteccion-solar-facial' => 'publicidad/contenido/nombre/eucerin',
        'eucerin-proteccion-solar-corporal' => 'publicidad/contenido/nombre/eucerin-corporal',
        'eucerin-proteccion-solar-infantil' => 'publicidad/contenido/nombre/eucerin-kids',
        'naturales' => 'publicidad/contenido/nombre/naturales',
        // 'energold-renergen-suplementos-dietarios' => 'publicidad/contenido/nombre/kyron-suplementos-dietarios',
        'energold-alimento-polvo' => 'publicidad/contenido/nombre/kyron-elimento-polvo',
        'energold-alimento-ninos' => 'publicidad/contenido/nombre/kyron-alimento-ninos',
        'gaviscon' => 'publicidad/contenido/nombre/gaviscon',
        'promocion-crem-helado-gafamania' => 'publicidad/contenido/nombre/crem-helado',
        'proteinas-healthy-sports' => 'publicidad/contenido/nombre/nutralab',
        'pomys-toallas-desmaquilladoras-piel-mixta' => 'publicidad/contenido/nombre/pommys-piel-mixta',
        'pomys-toallas-desmaquilladoras-piel-seca'  => 'publicidad/contenido/nombre/pommys-piel-normal-seca',
        'pomys-rueditas-desmaquilladoras' => 'publicidad/contenido/nombre/pommis-rueda-desmaquilladora',
        'strepsils-dolor-garganta' => 'publicidad/contenido/nombre/strepsil',
        'stamyl-forte-antiflatulento' => 'publicidad/contenido/nombre/stamyl',
        'milpax-antirreflujo' => 'publicidad/contenido/nombre/milpax',
        'calcibon-suplemento-calcio' => 'publicidad/contenido/nombre/calcibon',
        'igora-tintes-para-cabello' => 'publicidad/contenido/nombre/igora',
        'nutriben-crecimiento' => 'publicidad/contenido/nombre/nutriben',
        'baby-dove' => 'publicidad/contenido/nombre/baby-dove',
        'denticare-calendula-enjuague-bucal' => 'publicidad/contenido/nombre/denticare',
        'air-lift-elimina-mal-aliento' => 'publicidad/contenido/nombre/air-lift',
        'fybogel-fibra-para-estrenimiento' => 'publicidad/contenido/nombre/fybogel',
        'ky-lubricante-intimo' => 'publicidad/contenido/nombre/ky',
        'colgate-profesional' => 'publicidad/contenido/nombre/colgate-consultorio',
        'colgate-pacientes-con-gingivitis' => 'publicidad/contenido/nombre/colgate-gingivitis',
        'colgate-pacientes-con-sensibilidad' => 'publicidad/contenido/nombre/colgate-sensibilidad',
        'colgate-prevencion-caries' => 'publicidad/contenido/nombre/colgate-caries',
        'colgate-blanqueamiento-para-pacientes' => 'publicidad/contenido/nombre/colgate-blanqueamiento',
        'colgate-pacientes-con-ortodoncia' => 'publicidad/contenido/nombre/colgate-ortodoncia',
        'colgate-para-pequenos-pacientes' => 'publicidad/contenido/nombre/colgate-ninos',
        'choco-cono-millonario' => 'publicidad/contenido/nombre/chococono',
        //'klim1-deslactosado' => 'publicidad/contenido/nombre/klim1-deslactosado',
        'durex' => 'publicidad/contenido/nombre/durex',
        'klim3-fortilearn' => 'publicidad/contenido/nombre/klim3',
        'pantene-fuerza-y-reconstruccion' => 'publicidad/contenido/nombre/pantene',
        'shampoo-pantene-fuerza-y-reconstruccion' => 'publicidad/contenido/nombre/shampoo-pantene',
        'crema-para-peinar-pantene-fuerza-y-reconstruccion' => 'publicidad/contenido/nombre/crema-peinar-pantene',
        'acondicionador-diario-pantene-fuerza-y-reconstruccion' => 'publicidad/contenido/nombre/acondicionador-diario-pantene',
        'acondicionador-pantene-fuerza-y-reconstruccion' => 'publicidad/contenido/nombre/acondicionador-pantene',
        'nude-protectores-solares' => 'publicidad/contenido/nombre/nude-protector-solar',
        'nude-autobronceadores' => 'publicidad/contenido/nombre/nude-autobronceador',
        'nude-repelente-de-insectos' => 'publicidad/contenido/nombre/nude-repelente',
        'mejorflex-ibuprofeno' => 'publicidad/contenido/nombre/mejorflex',
        'gelicart-colageno-hidrolizado' => 'publicidad/contenido/nombre/gelicart',
        'asepxia' => 'publicidad/contenido/nombre/asepxia',
        'ni-una-dieta-mas' => 'publicidad/contenido/nombre/ni-una-dieta-mas',

        'cuidado-en-casa' => 'publicidad/contenido/nombre/cuidado-en-casa',
        'ayudas-de-movilidad' => 'publicidad/contenido/nombre/ayudas-de-movilidad',
        'control-y-prevencion' => 'publicidad/contenido/nombre/control-y-prevencion',
        'confort' => 'publicidad/contenido/nombre/confort',
        'equipos-terapia-respiratoria' => 'publicidad/contenido/nombre/equipos-terapia-respiratoria',
        'equipos-para-profesionales' => 'publicidad/contenido/nombre/equipos-para-profesionales',
        'productos-hospitalarios-y-quirurgicos' => 'publicidad/contenido/nombre/productos-hospitalarios-y-quirurgicos',
        'rehabilitacion-y-recuperacion' => 'publicidad/contenido/nombre/rehabilitacion-y-recuperacion',

         // Fin links campañas

        // REST patterns
        array('restProducto/producto', 'pattern' => 'rest/producto/<codigoProducto:\d+>/ciudad/<codigoCiudad:\d+>/sector/<codigoSector:\d+>', 'verb' => 'GET'),
        array('restCiudad/list', 'pattern' => 'rest/ciudad', 'verb' => 'GET'),
        array('restCiudad/view', 'pattern' => 'rest/ciudad/<id:\d+>', 'verb' => 'GET'),
        array('restPuntoVenta/puntoventacercano', 'pattern' => 'rest/puntoventacercano/lat/<lat:\-?\d+\.?\d+>/lon/<lon:\-?\d+\.?\d+>', 'verb' => 'GET'),
        array('restCiudad/sectores', 'pattern' => 'rest/ciudad/<id:\d+>/sectores', 'verb' => 'GET'),
        array('restPuntoVenta/list', 'pattern' => 'rest/puntoventa', 'verb' => 'GET'),
        array('restProducto/list', 'pattern' => 'rest/producto', 'verb' => 'GET'),
        array('restProducto/buscar', 'pattern' => 'rest/producto/buscar/<termino:.*>/<laboratorio:\-?\d+>', 'verb' => 'GET'),
        array('restProducto/simular', 'pattern' => 'rest/producto/simular', 'verb' => 'GET' ),
        array('restProfesion/ver', 'pattern' => 'rest/profesion/ver/<id:\d+>', 'verb' => 'GET'),
        array('restProfesion/listar', 'pattern' => 'rest/profesion', 'verb' => 'GET'),
    /* array('rest/update', 'pattern'=>'api/<model:\w+>/<id:\d+>', 'verb'=>'PUT'),
      array('rest/delete', 'pattern'=>'api/<model:\w+>/<id:\d+>', 'verb'=>'DELETE'),
      array('rest/create', 'pattern'=>'api/<model:\w+>', 'verb'=>'POST'), */
    // Other controllers
    // '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
    )
);
