<?php

return array(
    'urlFormat' => 'path',
    'showScriptName' => false,
    'caseSensitive' => true,
    'rules' => array(
        /* 'post/<id:\d+>/<title:.*?>'=>'post/view',
          'posts/<tag:.*?>'=>'post/index', */

        // Links de campañias
        'atacadol-alivio-dolores-fuertes' => 'publicidad/contenido/nombre/atacadol-alivio-dolores-fuertes',
        'coca-cola-sabores' => 'publicidad/contenido/nombre/coca-cola-sabores',
        'corega' => 'publicidad/contenido/nombre/corega',
        'klim-fortigrow' => 'publicidad/contenido/nombre/klim-fortigrow',
        'klim1-fortiprotect' => 'publicidad/contenido/nombre/leche-klim-1',
        'listerine' => 'publicidad/contenido/nombre/listerine-cuidado-total',
        'mas-informacion-metamucil' => 'publicidad/contenido/nombre/mas-informacion-metamucil',
        'metamucil-facilita-transito-intestinal' => 'publicidad/contenido/nombre/metamucil-facilita-transito-intestinal',
        'nestle-nan-optipro' => 'publicidad/contenido/nombre/nestle-nan-optipro',
        'recetas-nestle-nan-optipro' => 'publicidad/contenido/nombre/nan-recetas',
        'mas-informacion-nan' => 'publicidad/contenido/nombre/mas-informacion-nan',
        'parodontax' => 'publicidad/contenido/nombre/parodontax',
        'porque-elejir-metamucil' => 'publicidad/contenido/nombre/porque-elejir-metamucil',
        'prebioticos-klim' => 'publicidad/contenido/nombre/prebioticos-klim',
        'prohelix' => 'publicidad/contenido/nombre/prohelix',
        'sensodyne' => 'publicidad/contenido/nombre/sensodyne',
        'sobre-metamucil' => 'publicidad/contenido/nombre/sobre-metamucil',
        'perros-y-gatos' => 'publicidad/contenido/nombre/perros-y-gatos',
        'muestra-gratis-perros-y-gatos' => 'publicidad/contenido/nombre/perros-y-gatos-formulario',
        'proteccion-solar-sol-or' => 'publicidad/contenido/nombre/sol-or',
        'shampoo-clinical-solution-caspa-severa' => 'publicidad/contenido/nombre/pyg',
        'similac-mama-embarazo' => 'publicidad/contenido/nombre/similac-mama',
        'similac-3kid' => 'publicidad/contenido/nombre/similac-3-kid',
        'pediasure' => 'publicidad/contenido/nombre/pediasure',
        'ensure-nutricion-especializada' => 'publicidad/contenido/nombre/ensure',
        'glucerna-para-diabeticos' => 'publicidad/contenido/nombre/glucerna',
        'zahara-protector-solar' => 'publicidad/contenido/nombre/zahara',
        'prodent-cuidado-oral' => 'publicidad/contenido/nombre/prodent',
        'pedialyte-suero-oral' => 'publicidad/contenido/nombre/pedialyte',
        'pilas-energizer' => 'publicidad/contenido/nombre/energizer',
        'pilas-especiales-energizer' => 'publicidad/contenido/nombre/energizer-pilas-especiales',
        'condones-duo-sensaciones-extremas' => 'publicidad/contenido/nombre/duo-sensaciones-extremas',
        'condones-duo-maxima-sensacion' => 'publicidad/contenido/nombre/duo-maxima-sensacion',
        'condones-duo-seguridad-y-confianza' => 'publicidad/contenido/nombre/duo-seguridad-y-confianza',
        'altex-previene-acne' => 'publicidad/contenido/nombre/altex-previene',
        'altex-elimina-acne' => 'publicidad/contenido/nombre/altex-elimina',
        'altex-oculta-acne' => 'publicidad/contenido/nombre/altex-oculta',
        'cicatricure' => 'publicidad/contenido/nombre/cicatricure',
        'electrohogar' => 'publicidad/contenido/nombre/electrohogar',
        'nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum',
        'recetas-nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum-recetas',
        'sabias-que-nestum-cereales-infantiles' => 'publicidad/contenido/nombre/nestum-sabias-que',
        'eucerin-proteccion-solar-facial' => 'publicidad/contenido/nombre/eucerin',
        'eucerin-proteccion-solar-corporal' => 'publicidad/contenido/nombre/eucerin-corporal',
        'eucerin-proteccion-solar-infantil' => 'publicidad/contenido/nombre/eucerin-kids',
        'naturales' => 'publicidad/contenido/nombre/naturales',
        'energold-renergen-suplementos-dietarios' => 'publicidad/contenido/nombre/kyron-suplementos-dietarios',
        'energold-alimento-polvo' => 'publicidad/contenido/nombre/kyron-elimento-polvo',
        'energold-alimento-ninos' => 'publicidad/contenido/nombre/kyron-alimento-ninos',
        'gaviscon' => 'publicidad/contenido/nombre/gaviscon',
        'promocion-crem-helado-gafamania' => 'publicidad/contenido/nombre/crem-helado',
        'proteinas-healthy-sports' => 'publicidad/contenido/nombre/nutralab',
        'pomys-toallas-desmaquilladoras-piel-mixta' => 'publicidad/contenido/nombre/pommys-piel-mixta',
        'pomys-toallas-desmaquilladoras-piel-seca'  => 'publicidad/contenido/nombre/pommys-piel-normal-seca',
        'pomys-rueditas-desmaquilladoras' => 'publicidad/contenido/nombre/pommis-rueda-desmaquilladora',
        'strepsils-dolor-garganta' => 'publicidad/contenido/nombre/strepsil',
        'stamyl-forte-antiflatulento' => 'publicidad/contenido/nombre/stamyl',
        'milpax-antirreflujo' => 'publicidad/contenido/nombre/milpax',
        'calcibon-suplemento-calcio' => 'publicidad/contenido/nombre/calcibon',
        'igora-tintes-para-cabello' => 'publicidad/contenido/nombre/igora',
        'nutriben-crecimiento' => 'publicidad/contenido/nombre/nutriben',
        'baby-dove' => 'publicidad/contenido/nombre/baby-dove',
        'denticare-calendula-enjuague-bucal' => 'publicidad/contenido/nombre/denticare',
        'air-lift-elimina-mal-aliento' => 'publicidad/contenido/nombre/air-lift',

        // Fin links campañas

        // REST patterns
        array('restProducto/producto', 'pattern' => 'rest/producto/<codigoProducto:\d+>/ciudad/<codigoCiudad:\d+>/sector/<codigoSector:\d+>', 'verb' => 'GET'),
        array('restCiudad/list', 'pattern' => 'rest/ciudad', 'verb' => 'GET'),
        array('restCiudad/view', 'pattern' => 'rest/ciudad/<id:\d+>', 'verb' => 'GET'),
        array('restPuntoVenta/puntoventacercano', 'pattern' => 'rest/puntoventacercano/lat/<lat:\-?\d+\.?\d+>/lon/<lon:\-?\d+\.?\d+>', 'verb' => 'GET'),
        array('restCiudad/sectores', 'pattern' => 'rest/ciudad/<id:\d+>/sectores', 'verb' => 'GET'),
        array('restPuntoVenta/list', 'pattern' => 'rest/puntoventa', 'verb' => 'GET'),
        array('restProducto/list', 'pattern' => 'rest/producto', 'verb' => 'GET'),
        array('restProducto/buscar', 'pattern' => 'rest/producto/buscar/<termino:.*>/<laboratorio:\-?\d+>', 'verb' => 'GET'),
        array('restProducto/simular', 'pattern' => 'rest/producto/simular', 'verb' => 'GET' ),
        array('restProfesion/ver', 'pattern' => 'rest/profesion/ver/<id:\d+>', 'verb' => 'GET'),
        array('restProfesion/listar', 'pattern' => 'rest/profesion', 'verb' => 'GET'),
    /* array('rest/update', 'pattern'=>'api/<model:\w+>/<id:\d+>', 'verb'=>'PUT'),
      array('rest/delete', 'pattern'=>'api/<model:\w+>/<id:\d+>', 'verb'=>'DELETE'),
      array('rest/create', 'pattern'=>'api/<model:\w+>', 'verb'=>'POST'), */
    // Other controllers
    // '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
    )
);
