<div class='justify'> 
    <h2 class="center">TERMINOS DE USO.</h2>
    <p>Por  favor lee cuidadosamente el contenido de los siguientes textos. Por el uso de  este Sitio, aceptas los Términos de Uso, Términos del Contrato y Políticas de  Privacidad aquí contenidos.</p>
    <p> </p>
    <p>1.  Aceptación de Términos.</p>
    <p> </p>
    <p>Al  acceder, hojear y/o usar este sitio, el usuario admite haber leído y entendido  estos Términos de Uso y está de acuerdo en sujetarse a los mismos y cumplir con  todas las leyes y reglamentos aplicables que hagan parte de la Legislación  Colombiana. Además, cuando el usuario utilice cualquier servicio suministrado  en este Sitio, por ejemplo, \"Chat rooms\", buzones de sugerencias,  clasificados, concursos, estará sujeto a las reglas, guías, políticas, términos  y condiciones aplicables a dicho servicio. En caso de que el usuario no esté de  acuerdo con estos términos, favor abstenerse de usar este Sitio. Este Sitio es  controlado y operado por Copservir Ltda. Propietaria de los establecimientos de  La Rebaja Droguerías desde sus oficinas ubicadas en Colombia. Copservir Ltda. No  se responsabiliza de que el material en este Sitio sea apropiado o esté  disponible para su uso en otros lugares, estando prohibido su acceso desde  territorios donde su contenido sea ilegal. Aquellos que decidan accesar este  Sitio desde otros lugares lo harán bajo su propia iniciativa y es su  responsabilidad el sujetarse a las leyes locales que sean aplicables. Cualquier  reclamo con relación a, y al uso de, este Sitio y el material en él contenido  está regulado por las leyes de Colombia. Estos términos y condiciones están  sujetos a cambios sin previo aviso en cualquier momento, bajo la sola voluntad  de Copservir Ltda., y a partir de la fecha de modificación de estos términos y  condiciones, todas las operaciones que se celebren entre Copservir Ltda.  Propietaria de los establecimientos de Drogas la Rebaja y el usuario se regirán  por el documento modificado.</p>
    <p> </p>
    <p>2.  Encabezados.</p>
    <p> </p>
    <p>Los  encabezados de las cláusulas de estos Términos y Condiciones son únicamente  para facilitar la consulta y no forman parte de los mismos, y de ellos no se  podrán inferir o derivar ningún significado o interpretación.</p>
    <p> </p>
    <p>3.  Independencia de Disposiciones.</p>
    <p> </p>
    <p>En  caso de que una o más de las disposiciones contenidas en estos Términos y  Condiciones sean consideradas nulas, ilegales o ineficaces en cualquier  aspecto, la validez, legalidad, exigibilidad o eficacia del resto de las  disposiciones aquí contenidas no se verán afectadas o anuladas por dicha  circunstancia.</p>
    <p> </p>
    <p>4.  larebajavirtual.com.</p>
    <p> </p>
    <p>larebajavirtual.com  es un sitio web dedicado al comercio electrónico mediante la venta de productos  y/o servicios que se entregan exclusivamente en el territorio de la República  de Colombia. Larebajavirtual.com es de propiedad de Copservir Ltda.,  Cooperativa Multiactiva constituida bajo las leyes colombianas, cuya actividad  principal es la venta de medicamentos y productos especialmente despachados  desde los puntos de venta llamados Rebajas plus, al detal, constituyéndose en  una de las compañías más importantes en Colombia en dicho sector.</p>
    <p> </p>
    <p>5.  Derechos de Autor.</p>
    <p> </p>
    <p>Todo  el material informático, gráfico, publicitario, fotográfico, de multimedia,  audiovisual y/o de diseño, así como todos los contenidos, textos y bases de  datos puestos a su disposición en este Sitio son de propiedad exclusiva de  Copservir Ltda., o en algunos casos, de terceros que han autorizado a Copservir  Ltda. su uso y/o explotación (en adelante “los Contenidos”). Igualmente, el uso  en larebajavirtual de algunos Contenidos de propiedad de terceros se encuentra  expresamente autorizado por la ley. Todos los Contenidos en larebajavirtual  están protegidos por las normas sobre Derechos de Autor y por todas las normas  nacionales e internacionales que le sean aplicables. Exceptuando lo  expresamente estipulado en estos Términos y Condiciones, queda prohibido todo  acto de copia, reproducción, modificación, creación de trabajos derivados,  venta o distribución, exhibición de los Contenidos, de ninguna manera o por  ningún medio, incluyendo, más no limitado a, medios electrónicos, mecánicos, de  fotocopiado, de grabación o de cualquier otra índole, sin el permiso previo por  escrito de Copservir Ltda. o del titular de los derechos de autor. En ningún  caso estos Términos y Condiciones confieren derechos, licencias y/o  autorizaciones para realizar los actos anteriormente descritos. Cualquier uso  no autorizado de los Contenidos constituirá una violación a los presentes  Términos y Condiciones y a las normas vigentes sobre derechos de autor.  Copservir Ltda. otorga al usuario una licencia y derecho personal,  intransferible y no exclusivo para desplegar larebajavirtual en pantalla de un  computador ordenador o dispositivo PDA bajo su control, y para copiar los  Contenidos de propiedad de Copservir Ltda. únicamente para uso personal no  comercial intransferible, con la condición de que el usuario no modifique de  ninguna forma los Contenidos y que conserve todas las leyendas de derechos de  autor y de otro tipo de propiedad contenidas en los mismos. Esta licencia no se  extiende a la Propiedad Industrial de Copservir Ltda. Propietaria de los  establecimientos de La Rebaja Droguerías. o de terceros, y termina  automáticamente ante el incumplimiento del usuario de cualquiera de las  previsiones de estos Términos y Condiciones. Copservir Ltda. otorga al usuario  una licencia y derecho personal intransferible y no exclusivo para utilizar el  código objeto (no el código fuente) del software de larebajavirtual en un solo  computador pantalla u ordenador, y siempre que no copie, modifique, cree,  distribuya, reproduzca o exhiba un trabajo derivado de ello, invierta el  proceso, invierta el montaje o de algún modo intente descubrir algún código de  acceso, vender, ceder, sublicenciar, prestar garantía o transferir cualquier  derecho en el software delarebajavirtual. El usuario se obliga por los  presentes Términos y Condiciones a no modificar el software del Sitio de  ninguna manera.</p>
    <p> </p>
    <p>6.  Propiedad Industrial.</p>
    <p> </p>
    <p>Todas  las marcas, enseñas, logos, nombres y cualesquiera otros signos distintivos,  así como los modelos de utilidad y/o diseños industriales y demás elementos de  propiedad industrial o intelectual insertados, usados y/o desplegados en este  Sitio son Propiedad exclusiva de Copservir Ltda. Propietaria de los  establecimientos de La Rebaja Droguerías y en algunos casos son de propiedad de  terceros que han autorizado expresamente a Copservir Ltda. para su uso y/o  explotación. Igualmente, en algunos casos el uso de propiedad Industrial de  terceros ha sido autorizado por la ley de manera general, y en consecuencia su  uso no requiere de autorización previa y expresa de su titular. Nada en  larebajavirtual podrá ser interpretado como concesión u otorgamiento a cualquier  título de autorizaciones, licencias o cualquier otro derecho para usar o  disponer de cualquier forma de la Propiedad Industrial, sin el permiso por  escrito de Copservir Ltda. o del titular de los derechos de la misma. Cualquier  uso no autorizado constituirá una violación a los presentes Términos y  Condiciones y a las normas vigentes nacionales e internacionales sobre  Propiedad Industrial.</p>
    <p> </p>
    <p>7.  Linking, Deeplinking y Framing</p>
    <p> </p>
    <p>Copservir  Ltda. prohíbe el uso de los nombre y/o logotipos, marcas y cualesquiera otros  signos distintivos de su propiedad como enlaces hipertextuales o de cualquier  otra forma (\"links”) direccionados a sitios en Internet cuyo URL sea  diferente de <a href="http://www.larebajavirtual.com/">http://www.larebajavirtual.com</a>,  a menos que el establecimiento de un enlace de tal naturaleza sea aprobado por  Copservir Ltda. por escrito en cuyo caso deberá atenerse a los criterios y  manuales de diseño y publicidad establecidos por Copservir Ltda. Se reserva el  derecho de solicitar el retiro de enlaces que hayan sido establecidos en sitios  web sin su expresa y previa autorización. El establecimiento en páginas no  controladas por Copservir Ltda. de enlaces a subdirectorios dentro del URL <a href="http://www.larebajavirtual.com/">http://www.larebajavirtual.com</a>(Deeplinking)  queda prohibido. El despliegue, uso, exhibición, copia o cualquier otra forma  de reproducción del Sitio <a href="http://www.larebajavirtual.com/">http://www.larebajavirtual.com</a> o de cualquiera de sus subdirectorios  y/o páginas, en sitios no controlados por Copservir Ltda. (“Framing”) queda  expresamente prohibido. La inobservancia de estas prohibiciones será una  violación a los derechos de propiedad intelectual sobre los Contenidos y a los  derechos sobre la Propiedad Industrial.</p>
    <p> </p>
    <p>8.  Consultas.</p>
    <p> </p>
    <p>Cualquier  pregunta relacionada con el uso de marcas, enseñas, logos, signos distintivos y  en general de cualquier elemento de Propiedad Industrial del Sitio, así como  las relacionadas con el uso de los Contenidos o con el establecimiento de Links  hacia el URL <a href="http://www.larebajavirtual.com/">http://www.larebajavirtual.com</a> podrá ser hecha a Copservir Ltda. en  Colombia al teléfono 01800 93 99 00 o directamente a través de larebajavirtual.  Su uso, en contravención de lo aquí dispuesto, dará lugar a las acciones  civiles y penales correspondientes.</p>
    <p> </p>
    <p>9.  Exoneración y Garantías.</p>
    <p> </p>
    <p>De  conformidad con la Ley de la República de Colombia, el material contenido en  este Sitio, incluyendo sin limitación, textos, gráficos y vínculos (links), son  suministrados sobre la base de \"tal como es\" (\"as is\"),  sin haber de por medio garantías de cualquier tipo, ya sea expresas o  implícitas, incluyendo, mas no limitado a, garantías de comerciabilidad,  adecuación para un propósito particular, no contravención u otra violación de  derechos. Copservir Ltda. no garantiza el uso, validez, precisión o  confiabilidad de, o los resultados del uso de, o cualquier otra situación con  respecto a, el material en este Sitio o cualquier sitio web enlazado con este  Sitio.</p>
    <p> </p>
    <p>10.  Responsabilidad Limitada.</p>
    <p> </p>
    <p>Sin  perjuicio de lo determinado en las normas imperativas de la Legislación  Colombiana aplicable, Copservir Ltda. no asume responsabilidad alguna,  incluyendo cualquier responsabilidad por cualquier daño o perjuicio, incluyendo  mas no limitado a, pérdida de información o utilidades, existencia de virus,  resultados del uso o la incapacidad para usar el material en este Sitio,  oportunidades de negocios perdidas, o cualquier otro daño, aun cuando el usuario  nos haya avisado acerca de la posibilidad de tales daños, o por cualquier  reclamo de terceros, salvo lo que expresamente aquí se estipula. Bajo los  términos aquí señalados, Copservir Ltda. no asume ninguna responsabilidad por  la información que se suministra en la página, incluyendo pero sin limitarse a  la referente a productos y/o servicios, notas de interés, opiniones, consejos  prácticos y solución de inquietudes. Copservir Ltda no asume responsabilidad  alguna por la imposibilidad de, o por problemas en, la utilización del Sitio o  de alguna de las páginas que lo conforman, incluyendo pero sin limitarse a  eventos tales como problemas en el servidor o en la conexión, interrupciones en  su comunicación, problemas técnicos. En caso de que el uso del material de este  Sitio dé como resultado la necesidad de dar servicio a, reparar o corregir  equipo o información, el usuario asume cualquier costo derivado de ello.</p>
    <p> </p>
    <p>11.  Publicidad y vínculos.</p>
    <p> </p>
    <p>Las  organizaciones, productos y/o servicios a los cuales se les haga publicidad en  larebajavirtual, así como los vínculos (links) presentados en larebajavirtual  no son afiliados o tienen relación alguna con Copservir Ltda., y por tanto  Copservir Ltda no necesariamente apoya o promueve los productos y/o servicios,  o las organizaciones descritas en larebajavirtual. Copservir Ltda. no cumple  ninguna función en la producción de esos productos y/o la prestación de  servicios y no hace ninguna garantía, expresa o implícita de su contenido o de  su adecuación para un propósito particular. Así por ejemplo, cuando se sugiera  la utilización de algún producto y/o servicio, es de exclusiva autonomía del  usuario decidir su utilización, y por tanto, Copservir Ltda., no asume ninguna  responsabilidad por los perjuicios directos o indirectos, ciertos o eventuales,  pasados, presentes o futuros, que se llegaren a derivar de dicha utilización.  Así como que Copservir no se responsabiliza por la información colocada en  cuanto a prescripciones de los productos pues estos se ciñen a la información  colocada en los productos, así como a información del vademécum.Así las cosas,  los tratos que el usuario realice con el productor o proveedor de los productos  y/o servicios contenidos en la publicidad de este Sitio, así como las visitas  que realice a sus sitios web a través de los vínculos (links) de este Sitio,  serán por su exclusiva cuenta y riesgo, sin que de manera alguna comprometan la  responsabilidad de Copservir Ltda.</p>
    <p> </p>
    <p>12.  Revisión de los Términos.</p>
    <p> </p>
    <p>Copservir  Ltda. puede en cualquier momento revisar estos Términos de Uso aquí contenidos,  por medio de la actualización de este anuncio. Al usar larebajavirtual, el  usuario conviene en darse por obligado por cualquiera de tales revisiones, las  cuales estarán vigentes a partir del momento en que las mismas sean accesibles  por los Usuarios, debiendo entonces visitar periódicamente esta página para  determinar los términos vigentes en ese momento a los cuales el usuario estará  obligado en el evento que decida utilizar este Sitio.</p>
    <p> </p>
    <p>TERMINOS  DEL CONTRATO.</p>
    <p>Por  favor lee cuidadosamente el contenido de los siguientes textos. Por el uso de  este Sitio, aceptas los Términos de Uso, Términos del Contrato y Políticas de  Privacidad aquí contenidos.</p>
    <p> </p>
    <p>El  Contrato entre el cliente y Copservir Ltda. Propietaria de los establecimientos  de Drogas la Rebaja. Se perfeccionará cuando una Oferta de Compra en el Sitio  realizada por el cliente, sea aceptada por Copservir Ltda. El contrato estará  regido por los términos definidos en el presente texto, los cuales rigen la  venta de los productos y/o servicios que se realice mediante la utilización de  este Sitio por parte de Copservir Ltda. o cualesquiera de sus filiales,  subsidiarias o asociadas de negocios que aparezcan en la factura  correspondiente (en lo sucesivo indistintamente \" Copservir  Ltda.\"). Nuestros servicios están disponibles sólo para aquellos  individuos que tengan capacidad legal para contratar, según lo dispuesto por la  legislación colombiana vigente. Si el cliente no tiene capacidad legal para  contratar, le solicitamos que no utilice nuestros servicios. Copservir Ltda. en  ningún caso estará obligado a aceptar una Oferta de Compra.</p>
    <p> </p>
    <p>1.  Independencia de Disposiciones.</p>
    <p> </p>
    <p>En  caso de que una o más de las disposiciones contenidas en este documento sean  consideradas nulas, ilegales o ineficaces en cualquier aspecto, la validez,  legalidad y exigibilidad o eficacia del resto de las disposiciones del presente  documento, no se verán afectadas o anuladas por dicha circunstancia.</p>
    <p> </p>
    <p>2.Presentación  de Oferta.</p>
    <p> </p>
    <p>Copservir  Ltda. a través de larebajavirtual, extiende la invitación a ofertar por los  diferentes productos y servicios que se enuncian y/o describen en este Sitio  Web (\"Sitio\"). Para efectos de que exista una oferta de compra  válida por parte del cliente, se requiere del diligenciamiento por parte de  éste de una forma electrónica disponible en la página, en la cual se hará  constar los datos personales del cliente, la selección de los productos y/o  servicios deseados, la forma en que procederá a su pago, los datos que dependiendo  de la forma de pago sean necesarios para efectuar el mismo, así como los demás  datos que Copservir Ltda. considere necesarios para que se pueda proceder a  realizar una compra. Una vez se diligencia dicha forma electrónica, y la misma  haya sido recibida por Copservir Ltda., la Oferta del cliente se entenderá  perfecta y será obligatoria para el cliente. Copservir Ltda. procederá a  verificarla y decidir si acepta la misma. Ninguna Oferta obliga a Copservir  Ltda. sino hasta la aceptación de la misma. Toda cotización dada por Copservir  Ltda. será válida sólo para el momento en que se liquida el valor final de la  Oferta de compra, por lo que Copservir Ltda. se reserva el derecho de modificar  los precios de los productos en cualquier momento previo a la aceptación de la  Oferta, sin necesidad de avisar dicho cambio de ninguna manera.</p>
    <p> </p>
    <p>3.  Condiciones de Pago.</p>
    <p> </p>
    <p>Antes  de la aceptación por parte de Copservir Ltda. de cualquier Oferta de compra, el  cliente deberá elegir los términos y condiciones de pago del precio  correspondiente, según los medios de pago que se encuentran ya específicamente  establecidos en este Sitio. Aún cuando Copservir Ltda. Ponga a disposición del  cliente un sistema de conexión segura para toda la realización de todas las  ofertas de compra, en ningún caso Copservir Ltda. Será responsable por los  fallos en las comunicaciones de las entidades bancarias o de crédito, así como  tampoco de los daños causados a los usuarios con ocasión de una acción u  omisión de dichas entidades.Una vez que Copservir Ltda. verifique el pago,  podrá proceder a la aceptación de la Oferta de compra. En todo caso, no  obstante haberse verificado el pago, Copservir Ltda. podrá denegar la  aceptación de una Oferta de compra o aceptarla parcialmente, en cuyo caso sólo  estará obligado a restituirle al usuario, sin ningún tipo de interés o  rendimiento, el valor cancelado por la Oferta de compra no aceptada o el  porcentaje correspondiente a la parte no aprobada de una Oferta de compra  aceptada parcialmente. Copservir Ltda. podrá facturar partes de una misma  Oferta de compra de manera separada., Copservir Ltda. Informa en cada producto  si existe o no en el sitio de compra por tanto no se hace responsable de la  entrega o a la no aceptación del pedido, si el usuario escoge un producto que  no se vende en la población o lugar receptor del pedido, que aplica así mismo  para los productos o artículos que se venden en los negocios llamados Rebajas  Plus.</p>
    <p> </p>
    <p>4.  Cargos por Envío e Impuestos.</p>
    <p> </p>
    <p>El  cliente será responsable por los cargos de envío, manejo y seguro de los  productos y/o servicios que adquieran en larebajavirtual, así como de todos los  impuestos sobre ventas, impuestos al valor agregado y cualesquiera otros  impuestos y gravámenes que se ocasionen por cada Oferta de compra aceptada. Todos  los impuestos causados por la compra serán liquidados desde el momento en que  el cliente realiza su Oferta de compra en este Sitio, y por tanto podrá conocer  el valor exacto a pagar a favor de Copservir Ltda., el cual incluirá todos los  conceptos mencionados.</p>
    <p> </p>
    <p>5.  Perfeccionamiento y Transferencia de Propiedad.</p>
</div>